buildscript {
    repositories {
        maven { url 'https://jitpack.io'}
        google()
        mavenCentral()
        //maven {
        //    url = uri("https://storage.googleapis.com/r8-releases/raw")
        //}
    }
    dependencies {
        //gradle version packaged with AGP 8.5 causes crashes on Android 4.4-
        //this won't be needed once the bundled version is 8.7.2+
        //classpath 'com.android.tools:r8:8.13.19'
        classpath 'com.android.tools.build:gradle:9.1.0'
    }
}

allprojects {

    ext {
        appName = 'Eternity Pixel Dungeon'
        appPackageName = 'com.eternity.pixeldungeon.com'

        appVersionCode = 702
        appVersionName = 'v0.2.3'

        appJavaCompatibility = JavaVersion.VERSION_11

        appAndroidCompileSDK = 35   //Android 15
        appAndroidMinSDK = 21       //Android 5.0
        appAndroidTargetSDK = 35    //Android 15

        gdxVersion = '1.12.1'
        gdxControllersVersion = '2.2.4'
        robovmVersion = '2.3.24'
    }
    version = appVersionName

    repositories {
        //maven { url 'https://jitpack.io'}
        google()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }

}