plants.blandfruitbush.name=無味果
plants.blandfruitbush.desc=腐莓的遠親，來自無味果樹叢的梨狀產物，嚐起來猶如一團爐灰。果實粗糙且鬆軟，但並沒有毒性。也許可以煮食。
plants.blandfruitbush.discover_hint=此植物在地下城各處皆有可能出現。
plants.blandfruitbush$seed.name=無味果種子

plants.blindweed.name=致盲草
plants.blindweed.desc=在被碰到後，致盲草會瞬間枯萎並釋放一道強光。這道光足以刺傷受害者的雙眼，使其暫時失明。
plants.blindweed.warden_desc=_守望者_能將致盲草的能量轉化為暫時性的隱身護罩，而且不會被致盲。
plants.blindweed$seed.name=致盲草種子

plants.mageroyal.name=魔皇草
plants.mageroyal.refreshed=你感覺渾身清爽。
plants.mageroyal.desc=魔皇草的帶刺花朵含有一種化學物質，因其強大的中和性質而聞名。任何踏入這株植物的東西將會被淨化掉許多負面效果。
plants.mageroyal.warden_desc=當踩踏魔皇草時，_守望者_除了獲得中和效果以外，還能短暫地對所有環境影響免疫。
plants.mageroyal$seed.name=魔皇草種子

plants.earthroot.name=地縛根
plants.earthroot.desc=碰到地縛根後，它的根部會在你周邊形成某種無法移動的天然護甲。
plants.earthroot.warden_desc=地縛根的根部會隨_守望者_移動，成為攜帶式樹皮護甲。
plants.earthroot$seed.name=地縛根種子
plants.earthroot$armor.name=植被護甲
plants.earthroot$armor.desc=這是一種由層層樹皮和藤蔓盤結而成且不可移動的天然護甲。\n\n每當你受到物理攻擊時，植被護甲都會吸收%d點傷害，直到其耐久被耗盡並瓦解。\n\n該護甲是不可移動的，所以一旦你離開原位，護甲便會被破壞且變得無用。\n\n護甲剩餘量:%d點。

plants.fadeleaf.name=消逝草
plants.fadeleaf.desc=任何觸碰到消逝草的生物都會被傳送到當前層的一個隨機地點。
plants.fadeleaf.warden_desc=_守望者_能進一步發揮消逝草的空間魔力，直接回到上一層的下樓處。
plants.fadeleaf$seed.name=消逝草種子

plants.firebloom.name=綻焰花
plants.firebloom.desc=綻焰花被任何物品觸碰到時，都會化為一團火焰。
plants.firebloom.warden_desc=當_守望者_踐踏綻焰花時，她能將有害的火焰轉化為短暫的火焰之力。
plants.firebloom$seed.name=綻焰花種子

plants.icecap.name=霜冰冠
plants.icecap.desc=霜冰冠在被接觸到時會噴射出一團能冰凍周遭的花粉。潮溼環境下花粉的冰凍能力會大幅增強。
plants.icecap.warden_desc=當_守望者_踐踏霜冰冠時，她能將有害的冰凍轉化為短暫的霜凍之力。
plants.icecap$seed.name=霜冰冠種子

plants.plant.warden_desc=守望者踩踏這株植物不會獲得額外效果。
plants.plant.discover_hint=此植物由某種子生長而成，在地下城各處也有可能出現。
plants.plant$seed.seed_of=%s種子
plants.plant$seed.ac_plant=種植
plants.plant$seed.info=將這粒種子扔到你想種植它的地方。\n\n%s
plants.plant$seed$placeholder.name=種子

plants.rotberry.name=腐莓叢
plants.rotberry.desc=未成熟的腐莓灌木叢所結出的漿果嘗起來像是至人於死的甜味。經過幾年的生長，這棵灌木終會成熟為另一棵腐莓之心。被踩踏後，未成熟的腐莓會噴出少量的毒氣。
plants.rotberry.warden_desc=通常腐莓叢在遭到踐踏時，只會噴出少量毒氣，但_守望者_卻能聯結其中的魔力，在短時間內提升力量!
plants.rotberry.discover_hint=此植物由某種任務中得到的種子生長而成。
plants.rotberry$seed.name=腐莓種子
plants.rotberry$seed.discover_hint=此物品會在某任務中出現。

plants.sorrowmoss.name=斷腸苔
plants.sorrowmoss.desc=斷腸苔並不是一種苔蘚，而是一種有極強毒性，花瓣利如刀片的花。
plants.sorrowmoss.warden_desc=當_守望者_踐踏斷腸苔時，她能將有害的毒素轉化為短暫的毒性之力。
plants.sorrowmoss$seed.name=斷腸苔種子

plants.starflower.name=星隕花
plants.starflower.desc=星隕花極為罕見，據說其能夠為任何接觸它的單位賦予神聖之力。
plants.starflower.warden_desc=當_守望者_踐踏星隕花時，不僅能受到祝福，還能獲得顯著的法杖充能效果。
plants.starflower$seed.name=星隕花種子

plants.stormvine.name=風暴藤
plants.stormvine.desc=引力似乎並不能正常地作用在風暴藤上，它藍色的藤蔓能夠"掛"在空中。任何被風暴藤纏到的生物也被這種奇怪的引力影響，並失去方向感。
plants.stormvine.warden_desc=_守望者_能夠操縱風暴藤的魔力，在踐踏之後可以獲得短暫的漂浮能力。
plants.stormvine$seed.name=風暴藤種子

plants.sungrass.name=陽春草
plants.sungrass.desc=陽春草因其汁液緩慢但顯著的療傷效果而家喻戶曉。
plants.sungrass.warden_desc=_守望者_能將陽春草的治療魔力隨身攜帶。
plants.sungrass$seed.name=陽春草種子
plants.sungrass$health.name=草藥療養
plants.sungrass$health.desc=陽春草擁有優秀的治療能力，但治療速率比治療藥水慢很多。\n\n脫離植株將會打斷治療效果。\n\n剩餘治療量:%d。

plants.swiftthistle.name=速行薊
plants.swiftthistle.desc=被踩踏後，速行薊會加速周圍的時間流動，讓踩踏者可以瞬間行動數次。
plants.swiftthistle.warden_desc=當_守望者_踐踏速行薊時，不僅能獲得瞬間移動的機會，還能在短時間內極速奔跑。
plants.swiftthistle$seed.name=速行薊種子
plants.swiftthistle$timebubble.name=時間氣泡
plants.swiftthistle$timebubble.desc=這是一個加速時間運行的氣泡。 你可以在氣泡中瞬間進行多次行動，但是攻擊或施法都會打斷這個效果。 \n\n效果剩餘:%s回合。

# Eternity PD Fallback Keys
plants.blandfruitbush.name=blandfruit
plants.blandfruitbush.desc=Distant cousin of the rotberry, the pear-shaped produce of the blandfruit bush tastes like caked dust. The fruit is gross and unsubstantial but isn't poisonous. Perhaps it could be cooked.
plants.blandfruitbush$seed.name=seed of blandfruit
plants.blindweed.name=blindweed
plants.blindweed.desc=Upon being touched a blindweed perishes in a bright flash of light. The flash is strong enough to disorient for several seconds.
plants.blindweed.warden_desc=_The Warden_ will channel a blindweed's energy into a temporary shroud of invisibility, instead of being disoriented.
plants.blindweed$seed.name=seed of blindweed
plants.mageroyal.name=mageroyal
plants.mageroyal.refreshed=You feel refreshed.
plants.mageroyal.desc=The mageroyal's prickly flowers contain a chemical which is known for its properties as a strong neutralizing agent. Anything that steps in this plant will be cleansed of many negative effects.
plants.mageroyal.warden_desc=In addition to the neutralizing effect, _the Warden_ will become temporarily immune to all area-bound effects when stepping on mageroyal.
plants.mageroyal$seed.name=seed of mageroyal
plants.earthroot.name=earthroot
plants.earthroot.desc=When a creature touches an earthroot, its roots create a kind of immobile natural armor around it.
plants.earthroot.warden_desc=The roots of an earthroot plant will move with _the Warden_, providing her mobile barkskin armor.
plants.earthroot$seed.name=seed of earthroot
plants.earthroot$armor.name=herbal armor
plants.earthroot$armor.desc=A kind of natural, immobile armor made of bark and twine.\n\nThis herbal armor will block %d damage from any physical hit, until it eventually runs out of durability and collapses.\n\nAs the armor is immobile, moving will cause it to break apart and be lost.\n\nArmor remaining: %d.
plants.fadeleaf.name=fadeleaf
plants.fadeleaf.desc=Touching a fadeleaf will teleport any creature to a random place on the current level.
plants.fadeleaf.warden_desc=The teleportation effect of fadeleaf is more potent for _the Warden_, teleporting her back to the end of the previous dungeon level.
plants.fadeleaf$seed.name=seed of fadeleaf
plants.firebloom.name=firebloom
plants.firebloom.desc=When something touches a firebloom, it bursts into flames.
plants.firebloom.warden_desc=When she tramples a firebloom, _the Warden_ will be briefly imbued with flame instead of being harmed.
plants.firebloom$seed.name=seed of firebloom
plants.icecap.name=icecap
plants.icecap.desc=Upon being touched, an icecap lets out a puff of freezing pollen. The freezing effect is much stronger if the environment is wet.
plants.icecap.warden_desc=When she tramples an icecap, _the Warden_ will be briefly imbued with frost instead of being harmed.
plants.icecap$seed.name=seed of icecap
plants.plant.warden_desc=This plant has no special effect when used by the Warden.
plants.plant$seed.seed_of=seed of %s
plants.plant$seed.ac_plant=PLANT
plants.plant$seed.info=Throw this seed to the place where you want to grow a plant.\n\n%s
plants.plant$seed$placeholder.name=seed
plants.rotberry.name=rotberry
plants.rotberry.desc=The berries of a young rotberry shrub taste like sweet, sweet death. Over a few years, this rotberry shrub will grow into another rot heart. When trampled, a young rotberry will produce a small puff of toxic gas.
plants.rotberry.warden_desc=Normally a rotberry bush only produces a little gas when trampled, but _the Warden_ is able to harness energy from it to temporarily boost her strength!
plants.rotberry$seed.name=seed of rotberry
plants.sorrowmoss.name=sorrowmoss
plants.sorrowmoss.desc=A sorrowmoss is a flower (not a moss) with razor-sharp petals, coated with a deadly venom.
plants.sorrowmoss.warden_desc=When she tramples a sorrowmoss, _the Warden_ will be briefly imbued with toxin instead of being harmed.
plants.sorrowmoss$seed.name=seed of sorrowmoss
plants.starflower.name=starflower
plants.starflower.desc=A rare plant, starflower is said to grant holy power to whomever touches it.
plants.starflower.warden_desc=In addition to being blessed, _the Warden_ will gain a significant amount of wand recharging when she tramples a starflower.
plants.starflower$seed.name=seed of starflower
plants.stormvine.name=stormvine
plants.stormvine.desc=Gravity affects the stormvine plant strangely, allowing its whispy blue tendrils to 'hang' on the air. Anything caught in the vine is affected by this, and becomes disoriented.
plants.stormvine.warden_desc=_The Warden_ is able to control the gravitational effect of stormvine, and will briefly levitate when she tramples one.
plants.stormvine$seed.name=seed of stormvine
plants.sungrass.name=sungrass
plants.sungrass.desc=Sungrass is renowned for its sap's slow but effective healing properties.
plants.sungrass.warden_desc=_The Warden_ can receive healing from trampled sungrass even if she moves away from it.
plants.sungrass$seed.name=seed of sungrass
plants.sungrass$health.name=herbal healing
plants.sungrass$health.desc=Sungrass possesses excellent healing properties, though it is much slower than a potion of healing.\n\nMoving off the plant will break the healing effect.\n\nHealing remaining: %d.
plants.swiftthistle.name=swiftthistle
plants.swiftthistle.desc=When trampled, swiftthistle will briefly accelerate the flow of time around it, allowing the trampler to perform several actions instantly.
plants.swiftthistle.warden_desc=In addition to gaining instantaneous actions, _the Warden_ will also get a brief haste boost when trampling swiftthistle.
plants.swiftthistle$seed.name=seed of swiftthistle
plants.swiftthistle$timebubble.name=time bubble
plants.swiftthistle$timebubble.desc=A small bubble of accelerated time, allowing actions to be performed instantly. Attacking or using magic will break this effect however.\n\nTurns remaining: %s.
plants.blandfruitbush.discover_hint=You can find this plant randomly in the dungeon.
plants.plant.discover_hint=You can find this plant randomly in the dungeon, or grow it from its associated seed.
plants.rotberry.discover_hint=You can grow this plant from its associated seed during a specific quest.
