apply plugin: 'java-library'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.incremental = false
}

java.sourceCompatibility = java.targetCompatibility = appJavaCompatibility

dependencies {
    api project(':SPD-classes')
    implementation project(':services')
}
